# Generated by Django 4.1.7 on 2023-04-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_per',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
